import { useEffect, useState } from 'react'
import { CalendarDays, MapPin } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { StatusBadge } from '@/components/bookings/BookingCard'
import { ErrorState, SkeletonCard } from '@/components/ui/PageStates'
import { useToast } from '@/context/ToastContext'
import { getApiErrorMessage } from '@/lib/apiClient'
import { cancelBooking, getBooking } from '@/services/bookingService'

export default function BookingDetailsPage() { const { id } = useParams(); const navigate = useNavigate(); const { showToast } = useToast(); const [booking, setBooking] = useState(null); const [error, setError] = useState(''); const [cancelling, setCancelling] = useState(false)
    const load = () => getBooking(id).then(setBooking).catch((err) => setError(getApiErrorMessage(err, 'We could not load this booking.'))); useEffect(() => { load() }, [id]); const cancel = async () => { if (!window.confirm('Cancel this booking?')) return; setCancelling(true); try { await cancelBooking(id); showToast({ type: 'success', title: 'Booking cancelled', description: 'Your reservation has been cancelled.' }); load() } catch (err) { showToast({ type: 'error', title: 'Could not cancel booking', description: getApiErrorMessage(err) }) } finally { setCancelling(false) } }
    if (error) return <div className="px-4 pt-28"><ErrorState message={error} /></div>; if (!booking) return <div className="mx-auto max-w-4xl px-4 pt-28"><SkeletonCard className="h-96" /></div>; const cancellable = ['PAYMENT_PENDING', 'CONFIRMED'].includes(booking.status)
    return <div className="bg-slate-50/60 pt-24 pb-12 sm:pt-28"><div className="mx-auto max-w-4xl px-4 sm:px-6"><Link to="/bookings" className="text-sm font-bold text-rideon-blue hover:underline">← My bookings</Link><div className="mt-5 rounded-2xl border border-slate-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-wider text-slate-400">{booking.bookingNumber}</p><h1 className="mt-1 text-2xl font-extrabold text-rideon-dark">{booking.bike?.name || 'Campus ride'}</h1></div><StatusBadge status={booking.status} /></div><div className="mt-7 grid gap-4 border-y border-slate-100 py-5 sm:grid-cols-2"><div className="flex gap-3"><CalendarDays className="size-5 shrink-0 text-rideon-blue" /><div><p className="text-xs font-semibold text-slate-400">PICKUP</p><p className="mt-1 text-sm font-semibold text-slate-600">{new Date(booking.pickupAt).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}</p></div></div><div className="flex gap-3"><MapPin className="size-5 shrink-0 text-rideon-blue" /><div><p className="text-xs font-semibold text-slate-400">CAMPUS</p><p className="mt-1 text-sm font-semibold text-slate-600">{booking.campus?.name || 'Campus pickup'}</p></div></div></div><div className="mt-5 flex items-center justify-between"><div><p className="text-xs font-semibold text-slate-400">TOTAL</p><p className="text-xl font-extrabold text-rideon-dark">₹{Number(booking.totalAmount || 0).toLocaleString()}</p></div>{cancellable && <Button onClick={cancel} disabled={cancelling} variant="outline" className="border-red-200 text-red-600 hover:bg-red-50">{cancelling ? 'Cancelling…' : 'Cancel booking'}</Button>}</div>{booking.status === 'PAYMENT_PENDING' && <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-800">Payment is pending. Online payment will be available here in a future update.</p>}</div></div></div> }
