-- AlterTable
ALTER TABLE "bookings" ADD COLUMN     "helmetAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "helmetCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lateHelmetFee" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "system_settings" ADD COLUMN     "helmetFirstPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "helmetSecondPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "lateHelmetFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
